/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const TranslateLazyImport = createFileRoute('/translate')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const TranslateLazyRoute = TranslateLazyImport.update({
  path: '/translate',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/translate.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/translate': {
      id: '/translate'
      path: '/translate'
      fullPath: '/translate'
      preLoaderRoute: typeof TranslateLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexLazyRoute,
  TranslateLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/translate"
      ]
    },
    "/": {
      "filePath": "index.lazy.jsx"
    },
    "/translate": {
      "filePath": "translate.lazy.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
